/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    Breadcrumb: (typeof import("./../components/Breadcrumb/index.vue"))["default"];
    ElBreadcrumb: (typeof import("element-plus/es"))["ElBreadcrumb"];
    ElBreadcrumbItem: (typeof import("element-plus/es"))["ElBreadcrumbItem"];
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElCheckTag: (typeof import("element-plus/es"))["ElCheckTag"];
    ElDivider: (typeof import("element-plus/es"))["ElDivider"];
    ElDropdown: (typeof import("element-plus/es"))["ElDropdown"];
    ElDropdownItem: (typeof import("element-plus/es"))["ElDropdownItem"];
    ElDropdownMenu: (typeof import("element-plus/es"))["ElDropdownMenu"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElMenuItemGroup: (typeof import("element-plus/es"))["ElMenuItemGroup"];
    ElOption: (typeof import("element-plus/es"))["ElOption"];
    ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"];
    ElSelect: (typeof import("element-plus/es"))["ElSelect"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    ElTag: (typeof import("element-plus/es"))["ElTag"];
    Hamburger: (typeof import("./../components/Hamburger/index.vue"))["default"];
    IEpAddLocation: (typeof import("~icons/ep/add-location"))["default"];
    IEpCaretBottom: (typeof import("~icons/ep/caret-bottom"))["default"];
    IEpClose: (typeof import("~icons/ep/close"))["default"];
    IEpRight: (typeof import("~icons/ep/right"))["default"];
    IEpUser: (typeof import("~icons/ep/user"))["default"];
    Item: (typeof import("./../layout/components/Sidebar/Item.vue"))["default"];
    Link: (typeof import("./../layout/components/Sidebar/Link.vue"))["default"];
    Navbar: (typeof import("./../layout/components/Navbar/index.vue"))["default"];
    NavRight: (typeof import("./../layout/components/Navbar/NavRight.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Sidebar: (typeof import("./../layout/components/Sidebar/index.vue"))["default"];
    SidebarItem: (typeof import("./../layout/components/Sidebar/SidebarItem.vue"))["default"];
    SvgIcon: (typeof import("./../components/SvgIcon/index.vue"))["default"];
    TagsView: (typeof import("./../layout/components/TagsView/index.vue"))["default"];
  }
}
