/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    ElButton: (typeof import("element-plus/es"))["ElButton"];
    ElForm: (typeof import("element-plus/es"))["ElForm"];
    ElFormItem: (typeof import("element-plus/es"))["ElFormItem"];
    ElIcon: (typeof import("element-plus/es"))["ElIcon"];
    ElInput: (typeof import("element-plus/es"))["ElInput"];
    ElMenu: (typeof import("element-plus/es"))["ElMenu"];
    ElMenuItem: (typeof import("element-plus/es"))["ElMenuItem"];
    ElMenuItemGroup: (typeof import("element-plus/es"))["ElMenuItemGroup"];
    ElScrollbar: (typeof import("element-plus/es"))["ElScrollbar"];
    ElSubMenu: (typeof import("element-plus/es"))["ElSubMenu"];
    Item: (typeof import("./../layout/components/Sidebar/Item.vue"))["default"];
    Link: (typeof import("./../layout/components/Sidebar/Link.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    Sidebar: (typeof import("./../layout/components/Sidebar/index.vue"))["default"];
    SidebarItem: (typeof import("./../layout/components/Sidebar/SidebarItem.vue"))["default"];
  }
}
